[package]
name = "dsh-desktop-tauri"
version = "1.2.0"
description = "DeepSeek Harness Native Desktop Client Powered by Tauri v2"
authors = ["DSH Community"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2.0.5", features = [] }

[dependencies]
tauri = { version = "2.2.4", features = ["tray-icon", "wry"] }
tauri-plugin-opener = "2.2.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
url = "2.5"
windows = { version = "0.61.3", features = ["Win32_UI_WindowsAndMessaging"] }

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
